# Generated by Django 4.2.11 on 2024-08-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "documents",
            "0006_educationallink_downvotes_educationallink_upvotes_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="vote",
            name="link",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="user",
        ),
        migrations.AddField(
            model_name="document",
            name="downvotes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="document",
            name="upvotes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="LinkReport",
        ),
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
